arena_width: 400
arena_height: 400

headless: false
websocket_url: ws://127.0.0.1:3000
websocket_path: ws

agent_size: 2
initial_agent_layout: random
agents:
  - id: 1
    inputs: [bun]
    output: burger
  # - id: 1
  #   inputs: [lettuce]
  #   output: choppedlettuce
  # - id: 2
  #   inputs: [tomato]
  #   output: slicedtomato
  # - id: 3
  #   inputs: [bun, patty]
  #   output: plainburger
  # - id: 4
  #   inputs: [choppedlettuce, slicedtomato]
  #   output: salad
  # - id: 5
  #   inputs: [salad, plainburger]
  #   output: burger

station_size: 5
station_layout: circle
stations:
  - id: 1
    type: pickup
    resource: bun
  - id: 2
    type: dropoff
    resource: burger
  # - id: 1
  #   type: pickup
  #   resource: bun
  # - id: 2
  #   type: pickup
  #   resource: patty
  # - id: 3
  #   type: pickup
  #   resource: lettuce
  # - id: 4
  #   type: pickup
  #   resource: tomato
  # - id: 5
  #   type: dropoff
  #   resource: burger
  # - id: 6
  #   type: dropoff
  #   resource: plainburger
